backend:
  name: git-gateway
  accept_roles:
    - admin

media_folder: static/assets
public_folder: /assets

publish_mode: editorial_workflow

collections:
  - name: "work"
    label: "Work"
    folder: "blog"
    filter: {field: type, value: "work"}
    create: true
    format: frontmatter
    extension: "mdx"
    slug: "work-{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "select", options: ["work", "project"]  }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "project"
    label: "Project"
    folder: "blog"
    filter: {field: type, value: "project"}
    create: true
    format: frontmatter
    extension: "mdx"
    slug: "project-{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "select", options: ["work", "project"]  }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }